### PR TITLE
Minor tweaks and cleanup

### PR DESCRIPTION
**Pull request by XhmikosR**
@lukeapage: after this I could have a look at bumping clean-css and making the adaptation.

Also, this closes #17 since it includes a similar change.

### CODE REVIEW

**Comment by lukeapage** [comment]
I added you as a collaborater.. if you give me your npm username I can give you publishing permissions.

**Comment by XhmikosR** [comment]
Hey. I use the same username on npm just lowercase  (xhmikosr).

How do you want to proceed with the clean-css upgrade? I think I will merge
this and release a patch version and then look into the new clean-css.

**Comment by lukeapage** [comment]
Sounds good. I'm no longer involved much with less.js and have precious little time for o/s at the moment.

**Comment by XhmikosR** [comment]
I understand. No worries I'll make a few changes now that I have time for
open source.

**Comment by XhmikosR** [comment]
When you give me npm rights I'll publish a patch version and then look into the clean-css update.

I'd still like your opinion about dropping advanced and just use clean-css default which is O1.

**Pull request merged**
